#ifndef PLUSPLUSCHAT_ENUMS_
#define PLUSPLUSCHAT_ENUMS_

namespace PlusPlusChat {

	// DISCONNECTED -> CONNECTING -> CONNECTED -> JOINING -> CHATTING
	enum AppState {
		DISCONNECTED, CONNECTED, CHATTING, CONNECTING, JOINING
	};

	enum Action {
		INIT, TINI, ACK, ERR, CREATE, JOIN, GETROOMS, ROOMS, INVALID_ACTION
	};

}

#endif
