#ifndef PLUSPLUSCHAT_SHARED_ENUMS_
#define PLUSPLUSCHAT_SHARED_ENUMS_

enum Action {
	INIT, TINI, ERR, CREATE, JOIN, GETROOMS, ROOMS, JOINED, SEND, RECV, PING, PONG, GETHISTORY, HISTORY,INVALID_ACTION
};

#endif
